# Generated by Django 5.2.11 on 2026-02-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=120)),
                ('idempotency_key', models.CharField(max_length=120)),
                ('args_hash', models.CharField(max_length=64)),
                ('response_payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'storage_idempotency_record',
                'ordering': ['-created_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('tool_name', 'idempotency_key'), name='uniq_storage_idempotency_tool_key')],
            },
        ),
    ]
