# Generated by Django 5.2.11 on 2026-03-09 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_category_add_parent_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='repayment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
