# Generated by Django 5.2.11 on 2026-05-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('quadrant', models.CharField(choices=[('q1', '紧急且重要'), ('q2', '重要不紧急'), ('q3', '紧急不重要'), ('q4', '不紧急不重要')], default='q1', max_length=20)),
                ('category', models.CharField(choices=[('work', '工作'), ('study', '学习'), ('life', '生活'), ('finance', '财务'), ('health', '健康'), ('goal', '目标'), ('other', '其他')], default='other', max_length=50)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', '进行中'), ('done', '已完成')], default='pending', max_length=20)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'todos_item',
                'ordering': ['status', 'quadrant', 'sort_order', '-created_at'],
            },
        ),
    ]
