# Generated by Django 5.2.11 on 2026-02-26 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingItem',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('qty', models.IntegerField(default=1)),
                ('est_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('priority', models.CharField(choices=[('high', '高'), ('normal', '普通'), ('low', '低')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('pending', '待购'), ('done', '已购'), ('skipped', '跳过')], default='pending', max_length=20)),
                ('planned_date', models.CharField(blank=True, default='', max_length=20)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lists_shopping_item',
                'ordering': ['status', 'priority', '-created_at'],
            },
        ),
    ]
