# Generated by Django 5.2.11 on 2026-03-24 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_shoppingitem_actual_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionService',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('service_type', models.CharField(blank=True, default='', max_length=120)),
                ('billing_cycle', models.CharField(choices=[('monthly', '月度'), ('quarterly', '季度'), ('yearly', '年度'), ('custom', '自定义')], default='monthly', max_length=20)),
                ('custom_days', models.IntegerField(default=30)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('next_renewal_date', models.DateField()),
                ('status', models.CharField(choices=[('active', '进行中'), ('paused', '暂停'), ('cancelled', '已取消')], default='active', max_length=20)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lists_subscription_service',
                'ordering': ['next_renewal_date', 'name'],
            },
        ),
    ]
