# Generated by Django 5.2.11 on 2026-03-24 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_add_subscription_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionservice',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
