# Generated by Django 5.2.11 on 2026-03-24 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_subscription_add_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionservice',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
