# Generated by Django 5.2.11 on 2026-02-26 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='google', max_length=50)),
                ('api_base_url', models.CharField(blank=True, default='', max_length=500)),
                ('api_key', models.CharField(blank=True, default='', max_length=500)),
                ('model_name', models.CharField(default='gemini-1.5-flash', max_length=120)),
                ('system_prompt', models.TextField(default='你是专业个人财务顾问。请根据用户的收支、分类、趋势数据，输出可执行、可量化的消费建议。')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_advisor_config',
            },
        ),
    ]
